### ISSUE TITLE
Profile Picture Cannot Be Displayed Correctly

### ISSUE THREAD

**Issue by justapig9020** [TokyoHackerGirls/TokyoHackerGirls.github.io#2]
# Description
The profile picture cannot be displayed correctly in Simplified Chinese mode.

# Reproduce
[https://blog.thgirls.yt/zh-cn/关于少女们/](https://blog.thgirls.yt/zh-cn/%E5%85%B3%E4%BA%8E%E5%B0%91%E5%A5%B3%E4%BB%AC/)
<img width="866" alt="image" src="https://github.com/user-attachments/assets/4bcf7b19-0671-42d8-a6f5-a81fe54c901e">

# Tested Browsers
1. Arc
2. Safari

**Comment by CelDaemon** [comment]
Can be closed, seems to be fixed at https://blog.thgirls.yt/zh-cn/about-us/
